[project]
name = "ndcurves"
version = "1.1.5.1"
description = "Library for creating smooth cubic splines"
readme = "README.md"
license= "BSD-3-Clause"
dependencies = ["pin"]

[project.urls]
homepage = "https://github.com/loco-3d/ndcurves"

[tool.cmeel]
build-number = 1

[tool.black]
exclude = "cmake"

[build-system]
requires = [
    "cmeel[build]",
    "cmeel-eigen",
    "cmeel-urdfdom-headers",
    "cmeel-urdfdom-headers",
    "pin"
    ]
build-backend = "cmeel.build"
